# Generated by Django 3.2.6 on 2021-11-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, unique=True)),
                ('major', models.CharField(max_length=100, null=True)),
                ('is_club_leader', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
