# Generated by Django 3.2.6 on 2022-03-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20211102_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurant_manager',
            field=models.BooleanField(default=False),
        ),
    ]
