# Generated by Django 3.2.6 on 2022-04-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20220413_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_club_leader',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_restaurant_manager',
        ),
    ]
