# Generated by Django 3.2.6 on 2022-04-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_restaurant_manager'),
        ('user_auth', '0007_user_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
    ]
