# Generated by Django 3.2.6 on 2022-04-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_user_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restaurant',
        ),
    ]
