# Generated by Django 3.2.6 on 2021-11-15 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(choices=[('SEDS', 'SEDS'), ('SMG', 'SMG'), ('SSH', 'SSH'), ('NUSOM', 'NUSOM'), ('CPS', 'CPS')], default='SEDS', max_length=100)),
                ('terms', models.CharField(blank=True, max_length=100)),
                ('days', models.CharField(blank=True, max_length=10)),
                ('duration', models.IntegerField(choices=[(50, 50), (75, 75)], default=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.CharField(max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=256)),
                ('answer', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(choices=[('SEDS', 'SEDS'), ('SMG', 'SMG'), ('SSH', 'SSH'), ('NUSOM', 'NUSOM'), ('CPS', 'CPS')], default='SEDS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='syllabuses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sp_course.club')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(auto_now=True)),
                ('finish_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='sp_course.Instructor'),
        ),
    ]
