# Generated by Django 3.2.6 on 2021-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
    ]
