# Generated by Django 3.2.6 on 2021-11-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0004_alter_event_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
