# Generated by Django 3.2.6 on 2021-11-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0005_auto_20211116_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
