# Generated by Django 3.2.6 on 2021-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0006_deadline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='finish_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='start_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
