# Generated by Django 3.2.6 on 2021-11-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0007_auto_20211127_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='start_time',
        ),
    ]
