# Generated by Django 3.2.6 on 2021-12-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0008_remove_deadline_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(upload_to='syllabuses/'),
        ),
    ]
