# Generated by Django 3.2.6 on 2021-12-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0010_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
