# Generated by Django 3.2.6 on 2022-02-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0014_alter_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
