# Generated by Django 3.2.6 on 2022-04-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0016_course_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='alt_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
