# Generated by Django 3.2.6 on 2022-04-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0017_auto_20220405_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_time',
            field=models.CharField(default='09:50', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.CharField(default='09:00', max_length=10, null=True),
        ),
    ]
