# Generated by Django 3.2.6 on 2022-04-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0019_auto_20220405_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lab',
            name='days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lab',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='instructors',
            field=models.ManyToManyField(to='sp_course.Instructor'),
        ),
        migrations.AddField(
            model_name='lab',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='instructors',
            field=models.ManyToManyField(to='sp_course.Instructor'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recitation',
            name='days',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recitation',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recitation',
            name='instructors',
            field=models.ManyToManyField(to='sp_course.Instructor'),
        ),
        migrations.AddField(
            model_name='recitation',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
