# Generated by Django 3.2.6 on 2022-04-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_course', '0020_auto_20220406_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
